apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-96-tenant/load-app-8269ee05-6a43-4488-87c7-f4a49d538407/devfile-sample@sha256:433e10f10d72c10c5a939533637a15d8a4a77899cbaec4c687629c47fe110527
        name: my-nodejs
        resources: {}
status: {}
